# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"X\n\x12PrimeCheckResponse\x12\x0e\n\x06number\x18\x01 \x01(\x03\x12\x10\n\x08is_prime\x18\x02 \x01(\x08\x12\x0f\n\x07\x66\x61\x63tors\x18\x03 \x03(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t\"(\n\x0cRangeRequest\x12\x0b\n\x03min\x18\x01 \x01(\x03\x12\x0b\n\x03max\x18\x02 \x01(\x03\".\n\x0bPrimeNumber\x12\r\n\x05value\x18\x01 \x01(\x03\x12\x10\n\x08position\x18\x02 \x01(\x03\"\\\n\x17\x42\x61tchPrimeCountResponse\x12\x16\n\x0etotal_received\x18\x01 \x01(\x03\x12\x13\n\x0bprime_count\x18\x02 \x01(\x03\x12\x14\n\x0cprimes_found\x18\x03 \x03(\x03\x32\x9b\x02\n\x0b\x44\x65moService\x12;\n\nCheckPrime\x12\x13.demo.NumberRequest\x1a\x18.demo.PrimeCheckResponse\x12\x37\n\x0cStreamPrimes\x12\x12.demo.RangeRequest\x1a\x11.demo.PrimeNumber0\x01\x12J\n\x12\x43ountPrimesInBatch\x12\x13.demo.NumberRequest\x1a\x1d.demo.BatchPrimeCountResponse(\x01\x12J\n\x15InteractivePrimeCheck\x12\x13.demo.NumberRequest\x1a\x18.demo.PrimeCheckResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERREQUEST']._serialized_start=20
  _globals['_NUMBERREQUEST']._serialized_end=51
  _globals['_PRIMECHECKRESPONSE']._serialized_start=53
  _globals['_PRIMECHECKRESPONSE']._serialized_end=141
  _globals['_RANGEREQUEST']._serialized_start=143
  _globals['_RANGEREQUEST']._serialized_end=183
  _globals['_PRIMENUMBER']._serialized_start=185
  _globals['_PRIMENUMBER']._serialized_end=231
  _globals['_BATCHPRIMECOUNTRESPONSE']._serialized_start=233
  _globals['_BATCHPRIMECOUNTRESPONSE']._serialized_end=325
  _globals['_DEMOSERVICE']._serialized_start=328
  _globals['_DEMOSERVICE']._serialized_end=611
# @@protoc_insertion_point(module_scope)
