# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import demo_pb2 as demo__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in demo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DemoServiceStub:
    """============================================================
    Demo proto: demonstra os 4 tipos de comunicação do gRPC
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckPrime = channel.unary_unary(
                '/demo.DemoService/CheckPrime',
                request_serializer=demo__pb2.NumberRequest.SerializeToString,
                response_deserializer=demo__pb2.PrimeCheckResponse.FromString,
                _registered_method=True)
        self.StreamPrimes = channel.unary_stream(
                '/demo.DemoService/StreamPrimes',
                request_serializer=demo__pb2.RangeRequest.SerializeToString,
                response_deserializer=demo__pb2.PrimeNumber.FromString,
                _registered_method=True)
        self.CountPrimesInBatch = channel.stream_unary(
                '/demo.DemoService/CountPrimesInBatch',
                request_serializer=demo__pb2.NumberRequest.SerializeToString,
                response_deserializer=demo__pb2.BatchPrimeCountResponse.FromString,
                _registered_method=True)
        self.InteractivePrimeCheck = channel.stream_stream(
                '/demo.DemoService/InteractivePrimeCheck',
                request_serializer=demo__pb2.NumberRequest.SerializeToString,
                response_deserializer=demo__pb2.PrimeCheckResponse.FromString,
                _registered_method=True)


class DemoServiceServicer:
    """============================================================
    Demo proto: demonstra os 4 tipos de comunicação do gRPC
    ============================================================

    """

    def CheckPrime(self, request, context):
        """1) UNARY: cliente envia 1 request, servidor responde 1 response
        Uso: verificar se um único número é primo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPrimes(self, request, context):
        """2) SERVER STREAMING: cliente envia 1 request, servidor responde com stream
        Uso: cliente pede um intervalo, servidor envia os primos um por um
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountPrimesInBatch(self, request_iterator, context):
        """3) CLIENT STREAMING: cliente envia stream de requests, servidor responde 1 vez
        Uso: cliente envia vários números, servidor retorna quantos são primos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InteractivePrimeCheck(self, request_iterator, context):
        """4) BIDIRECTIONAL STREAMING: ambos trocam streams simultaneamente
        Uso: cliente envia números interativamente, servidor responde a cada um
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckPrime': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPrime,
                    request_deserializer=demo__pb2.NumberRequest.FromString,
                    response_serializer=demo__pb2.PrimeCheckResponse.SerializeToString,
            ),
            'StreamPrimes': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrimes,
                    request_deserializer=demo__pb2.RangeRequest.FromString,
                    response_serializer=demo__pb2.PrimeNumber.SerializeToString,
            ),
            'CountPrimesInBatch': grpc.stream_unary_rpc_method_handler(
                    servicer.CountPrimesInBatch,
                    request_deserializer=demo__pb2.NumberRequest.FromString,
                    response_serializer=demo__pb2.BatchPrimeCountResponse.SerializeToString,
            ),
            'InteractivePrimeCheck': grpc.stream_stream_rpc_method_handler(
                    servicer.InteractivePrimeCheck,
                    request_deserializer=demo__pb2.NumberRequest.FromString,
                    response_serializer=demo__pb2.PrimeCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.DemoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.DemoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DemoService:
    """============================================================
    Demo proto: demonstra os 4 tipos de comunicação do gRPC
    ============================================================

    """

    @staticmethod
    def CheckPrime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.DemoService/CheckPrime',
            demo__pb2.NumberRequest.SerializeToString,
            demo__pb2.PrimeCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPrimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/demo.DemoService/StreamPrimes',
            demo__pb2.RangeRequest.SerializeToString,
            demo__pb2.PrimeNumber.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountPrimesInBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/demo.DemoService/CountPrimesInBatch',
            demo__pb2.NumberRequest.SerializeToString,
            demo__pb2.BatchPrimeCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InteractivePrimeCheck(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/demo.DemoService/InteractivePrimeCheck',
            demo__pb2.NumberRequest.SerializeToString,
            demo__pb2.PrimeCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
